### ISSUE TITLE
How to get pairs.txt? Can it be provided?

### ISSUE THREAD

**Issue by Zirconium2159** [ShawnXYang/TIP-IM#2]
pairs.txt is initial for training but it is missed in the repo.

**Comment by ShawnXYang** [comment]
As for 'pairs.txt', you can search for this file in http://vis-www.cs.umass.edu/lfw/#download.

**Comment by mengxinZHANG** [comment]
> pairs.txt is initial for training but it is missed in the repo.

Hello,I'm also paying attention to this code.But I found a balance between MMD loss and loss_i(loss_t) is a problem,How do you set "gamma"? thanks.
