### ISSUE TITLE
What's the datset that you have used for training the face recognition model?

### ISSUE THREAD

**Issue by GeorgeCarpenter** [ShawnXYang/TIP-IM#8]
Thanks.

**Comment by ShawnXYang** [comment]
Hi, the trained models are based on the MS-Celeb-1M dataset.

**Comment by GeorgeCarpenter** [comment]
Could you tell us the size of the input images for these face recognition models?

**Comment by GeorgeCarpenter** [comment]
> Could you tell us the size of the input images for these face recognition models?

The paper write:
```
In experiments, we first use MTCNN [53] to detect faces in the image, then align the images and crop them to 112 × 112, meaning that the identity masks are executed only in the face area.
```
However, we have tried the pre-trained models you have provided. We found that the size of the input images of  ArcFace is (112, 96).

Could you release the correct model you have used whose size of the input images is (112, 112)?

**Comment by ShawnXYang** [comment]
Please refer to https://github.com/ShawnXYang/TIP-IM/blob/master/get_model.py#L19 . We further adaptively resize these images because the input requirement of each pre-trained model is different.
